name: Publish trade-bot__db-types Package
on: 
  push:
    branches: [master]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Installing Node Modules
        run: npm install
      - name: Generating Types for DataBase
        run: npm run db-update
      - run: node ./.github/scripts/get-db-types.js
      - run: node ./.github/scripts/gen-db-types-package-json.js
      - name: Push to db-types repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.PACKAGES_TOKEN }}
        with:
          source-directory: 'tmp/trade-bot-db-types'
          destination-github-username: 'badlabs'
          destination-repository-name: 'trade-bot__db-types'
          user-name: d0rich
          user-email: dorich2000@gmail.com
          target-branch: master

  package:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Locate to Package Folder
        run: cd ./tmp/trade-bot__db-types
      - run: npm version prerelease --preid=ci-$GITHUB_RUN_ID --no-git-tag-version
      - run: npm pack
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
            name: trade-bot__db-types
            path: "*.tgz"
  publish:
    name: "Publish to GitHub Packages"
    needs: [package]
    runs-on: ubuntu-latest
    if: github.repository_owner == 'badlabs'
    steps:
    - name: Locate to Package Folder
      run: cd ./tmp/trade-bot__db-types
    - name: Upload
      uses: actions/download-artifact@v2
      with:
          name: trade-bot__db-types
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        registry-url: https://npm.pkg.github.com/
        scope: "@badlabs"
    - run: echo "registry=https://npm.pkg.github.com/@badlabs" >> .npmrc
    - run: npm publish $(ls *.tgz)
      env:
        NODE_AUTH_TOKEN: ${{secrets.PACKAGES_TOKEN}}
