name: Publish trade-bot__db-types Package
on: 
  push:
    branches: [master]
  workflow_dispatch:
jobs:
  update-db-types:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Node Modules
        run: npm ci
      - name: Generate Types for Database
        run: npm run db-update
      - name: Download trade-bot__db-types
        uses: actions/checkout@v3
        with:
          repository: badlabs/trade-bot__db-types
          path: ./tmp/trade-bot__db-types
      - name: Extract Types to Special Directory
        run: node ./.github/scripts/get-db-types.js
      - name: Generate package.json
        run: node ./.github/scripts/gen-db-types-package-json.js
      - name: Push to db-types repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.PACKAGES_TOKEN }}
        with:
          source-directory: 'tmp/trade-bot__db-types'
          destination-github-username: 'badlabs'
          destination-repository-name: 'trade-bot__db-types'
          user-name: d0rich
          user-email: dorich2000@gmail.com
          target-branch: master